# fly.toml app configuration file generated for dark-snow-1832 on 2023-10-10T16:56:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dark-snow-1832"
primary_region = "ord"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[env]
  PHX_HOST = "dark-snow-1832.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
